"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import Link from "next/link";
import { Search,X } from "lucide-react";
type Result={type:string;label:string;href:string};
export function GlobalSearch(){const[open,setOpen]=useState(false);const[query,setQuery]=useState("");const[results,setResults]=useState<Result[]>([]);const inputRef=useRef<HTMLInputElement>(null);const close=useCallback(()=>{setOpen(false);setQuery("");setResults([])},[]);
useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setOpen(true)}if(event.key==="Escape")close()};document.addEventListener("keydown",handler);return()=>document.removeEventListener("keydown",handler)},[close]);
useEffect(()=>{if(open)inputRef.current?.focus()},[open]);
useEffect(()=>{if(query.trim().length<2)return;let active=true;const timer=window.setTimeout(async()=>{const response=await fetch(`/api/search?q=${encodeURIComponent(query)}`);if(response.ok&&active)setResults((await response.json()).data)},180);return()=>{active=false;window.clearTimeout(timer)}},[query]);
const visibleResults=query.length>=2?results:[];
return <><button onClick={()=>setOpen(true)} className="flex h-9 w-full items-center gap-2 rounded-xl border border-white/[.07] bg-white/[.035] px-3 text-left text-xs text-slate-500 hover:border-white/[.13] hover:bg-white/[.055]"><Search size={14}/><span className="flex-1">Search Pokémon, moves, teams…</span><kbd className="rounded-md border border-white/10 bg-black/20 px-1.5 py-0.5 text-[10px]">Ctrl K</kbd></button>{open&&<div className="fixed inset-0 z-[80] bg-black/70 p-4 pt-[12vh] backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="Global search" onMouseDown={(e)=>{if(e.target===e.currentTarget)close()}}><div className="surface mx-auto max-w-xl overflow-hidden shadow-2xl"><div className="flex items-center gap-3 border-b p-4"><Search size={18} className="text-violet-400"/><input ref={inputRef} value={query} onChange={(e)=>setQuery(e.target.value)} className="w-full bg-transparent text-base outline-none" placeholder="Search verified Champions data…"/><button onClick={close} aria-label="Close search"><X size={18}/></button></div><div className="max-h-[55vh] overflow-y-auto p-2">{query.length<2&&<p className="muted p-6 text-center text-sm">Enter at least two characters.</p>}{query.length>=2&&visibleResults.length===0&&<p className="muted p-6 text-center text-sm">No matching verified records.</p>}{visibleResults.map((result)=><Link key={`${result.type}-${result.href}`} href={result.href} onClick={close} className="flex items-center justify-between rounded-lg px-3 py-3 text-sm hover:bg-white/[.05]"><span>{result.label}</span><span className="badge">{result.type}</span></Link>)}</div></div></div>}</>}
